FROM node:16 as frontend

WORKDIR /app/frontend
COPY frontend/ ./
RUN apt-get update && apt-get install -y nginx

FROM python:3.9-slim

RUN apt-get update && apt-get install -y nginx

COPY --from=frontend /app/frontend /usr/share/nginx/html

WORKDIR /app/backend

COPY backend/ ./backend

COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
EXPOSE 80

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "5000"]